1.144.120

diff --git a/.github/workflows/latest.json.yml b/.github/workflows/latest.json.yml
--- a/.github/workflows/latest.json.yml
+++ b/.github/workflows/latest.json.yml
@@ -13,15 +13,15 @@ jobs:
 
       - name: Wait for URL to be available
         run: |
-          while ! curl -s "https://github.com/kamranmuazzam/im19result/releases/download/1.144.120/latest.json" | grep -q '{"error":"Not Found"}'; do
+          while ! curl -s "https://github.com/kamranmuazzam/im19result/releases/download/v1.144.120/latest.json" | grep -q '{"error":"Not Found"}'; do
               sleep 10
-              echo "Waiting for URL to return 'Not Found' error..."
+              echo "Waiting For Build"
           done
 
       - name: Download latest.json
         run: |
           rm latest.json
-          curl -LJO "https://github.com/kamranmuazzam/im19result/releases/download/1.114.115/latest.json"
+          curl -LJO "https://github.com/kamranmuazzam/im19result/releases/download/v1.114.120/latest.json"
 
       - name: Configure Git
         run: |
