1.144.120

diff --git a/.github/workflows/latest.json.yml b/.github/workflows/latest.json.yml
--- a/.github/workflows/latest.json.yml
+++ b/.github/workflows/latest.json.yml
@@ -13,7 +13,7 @@ jobs:
 
       - name: Wait for URL to be available
         run: |
-          while ! curl -s --output /dev/null --silent --head --fail "https://github.com/kamranmuazzam/im19result/releases/download/1.144.120/latest.json" | grep -q '{"error":"Not Found"}'; do
+          while ! curl -s "https://github.com/kamranmuazzam/im19result/releases/download/1.144.120/latest.json" | grep -q '{"error":"Not Found"}'; do
               sleep 10
               echo "Waiting for URL to return 'Not Found' error..."
           done
